### ISSUE TITLE
"Securely logging in" animation when user enters their password

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#445]
Current: 
Users encounter a 1-2 second delay after entering their wallet password, a consequence of a security feature which prevents brute force attacks during login. 

Problem:
The delay is not an optimal user experience - customers expect speed and performance.

Solution:
Add an attractive loading animation after a successful password submission. The animation will indicate that a 'secure log in' event is taking place. We need to shift the perspective of the user - they are not opening a flimsy lockbox but a heavy, steel vault. Let them know that the delay is a consequence of sophisticated security - a feature not a bug.

Animation can be viewed here:
https://makellc.slack.com/archives/C026E4N640N/p1674327520107679

Figma is here:
https://www.figma.com/file/mBlqs6l6I2d3ihX80Mswm4/Casper-Wallet-(Develop)?node-id=4309%3A8465&t=FTzWmJ216rsmaFI1-11

**Comment by adammake** [comment]
I've added a design ticket for this: I've added a design ticket for this https://make-software.atlassian.net/browse/DESIGN-12

**Comment by piotrwitek** [comment]
Resolved by #639
