### ISSUE TITLE
Account info standard support

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#480]
We should support Account info standard support, which is an API that returns user-defined account meta data based on public key.
From that metadata we'll need to use account name and icon to show in the wallet home page and account lists, similar to what CSPR.live is doing.
Just take a look at the code from CSPR.live codebase on account page and implement the same.

**Comment by don-truong** [comment]
Migrated to [this ticket](https://app.zenhub.com/workspaces/casper-wallet-61e1eff68a7f850022d10cc1/issues/gh/make-software/casper-wallet/628).
