### ISSUE TITLE
Casper Wallet | Account info standard support | Can't to switch to account with changed name 

### ISSUE THREAD

**Issue by ost-ptk** [make-software/casper-wallet#566]
We can't switch to an account with a changed name
The account name wasn't changed when we try to connect to the dapp.
The account name wasn't changed when we try to switch accounts in the dapp.

https://user-images.githubusercontent.com/44294945/222741852-f4446363-4a2f-4bf5-a831-b6af9f820981.mov

**Comment by piotrwitek** [comment]
Fixed by #628

**Comment by piotrwitek** [comment]
@karatnyk this should be fixed now with new account info standard changes implemented

**Comment by karatnyk** [comment]
Verified on build 1.3.0 as fixed, moving to 'Done'.
