### ISSUE TITLE
Handle large balances cleanly in Casper Wallet

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#593]
**Problem**
With the support of decimals in CSPR balances, the balance value on the home screen can become quite large. 

**Solution**
The home screen design should be updated to better handle large balance values without breaking the UI layout.

- Dynamic font resizing based on the number of characters in the balance
- Define breakpoints for font shifts (e.g. at 10 characters, font size is X, at 20 characters, font size is Y, etc)

**Comment by karatnyk** [comment]
I've completely forgot to mark this ticket as "Done" - it is successfully implemented :)
