### ISSUE TITLE
[Safari] Private key download disabled message

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#611]
Due to a technical constraint, Safari users will not be able to download their imported secret key files in the Casper Wallet launch build. The long term fix will be addressed in #612. We need a simple solution to address the issue until the long term fix can be implemented.

Solution

1.1Messaging will be added to Casper Wallet to let users know that private keys cannot be downloaded. This message will only appear for Safari users.
In the import screen: "Please note, accounts imported with a file cannot be recovered using your Casper Wallet secret recovery phrase. 
Important: After importing, private key files cannot be downloaded from Casper Wallet. Make sure to store a copy of your secret key file in a safe place.
![image.png](https://images.zenhubusercontent.com/61e1ac21d1fded72df402cc1/8731de8f-0089-4335-91df-a44bb3122c3b)

1.2
Hide the "Download secret key file" in the Settings menu option.

**Comment by karatnyk** [comment]
@piotrwitek 
Within build 1.3.0 "Private key download" functionality is disabled not only for Safari but for Firefox browser as well (though it worked on previous builds), could you please advise if this is expected?
![firefox_tXRfTdy2Jx.gif](https://images.zenhubusercontent.com/6241d5bd38a85b3df1624280/2c4a1bd9-8fbf-47fe-8458-7d3739b70b9a)

**Comment by piotrwitek** [comment]
Thanks @karatnyk It should work on Firefox. 
@ost-ptk could you have a look?

**Comment by karatnyk** [comment]
@piotrwitek 
In that case, I'll move this ticket back to "In Progress".

**Comment by karatnyk** [comment]
Verified on latest 1.3.0 build as fixed, marking this ticket as "Done".
