### ISSUE TITLE
Terms and Privacy Policy links should open in a new tab

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#624]
Current
During onboarding, clicking on Terms of Service of Privacy Policy links opens those links in the same window, killing the onboarding flow.

Expected
Clicking on Terms of Service or Privacy Policy links should always open those links in a new tab.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/97249036/230813162-232be625-9e60-4786-8821-ae79e5d5eae9.png">

**Comment by karatnyk** [comment]
Moving to 'Done' as successfully implemented in build 1.3.0
