### ISSUE TITLE
Identicon/avatar UI improvements

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#636]
- The account image should be rounded.
- Texts on the buttons are too thin. Make them according to design.
- Connected (on account card) should be centred in the green container, but now it’s not.

![image.png](https://images.zenhubusercontent.com/61e1ac21d1fded72df402cc1/4e27cec4-1faa-48b2-8df7-6d18d018b0ea)

https://makellc.slack.com/archives/C026E4N640N/p1681681736336879?thread_ts=1681681444.886859&cid=C026E4N640N

**Comment by ost-ptk** [comment]
> * Texts on the buttons are too thin. Make them according to design.

I checked on 4 browsers (Chrome, Firefox, Safari, Edge), and in each, the buttons are bold as in Figma

@adammake

**Comment by karatnyk** [comment]
Moving to 'Done' as successfully implemented in build 1.3.0
