### ISSUE TITLE
Remove black cross from 'not connected' screen graphic

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#637]
There should not be a black cross inside this icon. Let’s export this illustration again. Yulia can help if needed.

![image.png](https://images.zenhubusercontent.com/61e1ac21d1fded72df402cc1/3e3fff17-fe79-4525-80e9-67fa5bd37cf6)

**Comment by ost-ptk** [comment]
There is some problem with a few icons where are red circles and a white cross. Sent a message to Yulia about this. Wait for a response

**Comment by ost-ptk** [comment]
Done #648

**Comment by karatnyk** [comment]
Moving to 'Done' as successfully implemented in build 1.3.0 
![image.png](https://images.zenhubusercontent.com/6241d5bd38a85b3df1624280/92938583-9ce0-4b3a-b203-4823290a9bab)
