### ISSUE TITLE
Improve Unlock Wallet User Experience

### ISSUE THREAD

**Issue by piotrwitek** [make-software/casper-wallet#639]
On the vault unlock page when the user successfully entered the password we should add an unlock animation, this would minimize the perceived delay needed to decrypt the vault.

Design: https://www.figma.com/file/mBlqs6l6I2d3ihX80Mswm4/Casper-Wallet-%E2%80%93-Extension?node-id=5539%3A12166&t=kMDtHazTXP1H6vlH-1
Animation file: https://lottiefiles.com/63686-lock-animation

**Comment by adammake** [comment]
Added to Jira https://make-software.atlassian.net/browse/WALLET-50

**Comment by adammake** [comment]
Need animation positioning and playback details from design team.
