### ISSUE TITLE
Align group names in Settings menu

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#643]
The alignment of group names (ACCOUNT, SETTING, SECURITY, ETC.) is wrong. Take right alignment from Figma file.

![image.png](https://images.zenhubusercontent.com/61e1ac21d1fded72df402cc1/482ff990-a45c-4082-a5b9-33234229f890)

![image.png](https://images.zenhubusercontent.com/61e1ac21d1fded72df402cc1/0d7fb300-6be7-44fe-8485-033e6d4ccf30)

**Comment by ost-ptk** [comment]
Done #645

**Comment by karatnyk** [comment]
Moving to 'Done' as successfully implemented in build 1.3.0
