### ISSUE TITLE
[Safari] Casper Wallet | Can't sign in on to cspr.live with casper wallet

### ISSUE THREAD

**Issue by ost-ptk** [make-software/casper-wallet#650]
Pre-conditions:
A vault with an account exists

Steps to reproduce:

1. Open Safari and unlock wallet
2. Go to cspr.live
3. Try to sign in

Casper Wallet 1.2.6

Expected result: You sign in to the dapp and wallet shows that you connected
Actual result: Wallet shows that you connected but dapp doesn't

https://user-images.githubusercontent.com/44294945/233650625-2ca8a37d-c560-44b9-b2f5-106ccdcb8546.mov

Also, I noticed such strange behavior when trying to reproduce this bug

<img width="357" alt="Знімок екрана 2023-04-21 о 16 44 55" src="https://user-images.githubusercontent.com/44294945/233652142-11ad419c-5e06-4157-b43d-6d3c491a0eb5.png">

**Comment by ost-ptk** [comment]
<img width="357" alt="Знімок екрана 2023-04-25 о 16 32 42" src="https://user-images.githubusercontent.com/44294945/234305298-e54b6a74-5c73-4587-be39-aacd539b627e.png">
<img width="1164" alt="Знімок екрана 2023-04-25 о 17 16 12" src="https://user-images.githubusercontent.com/44294945/234305309-a5e9bd17-0528-4e57-8754-b23da4e8a6a2.png">

**Comment by adammake** [comment]
Closing in favor of https://make-software.atlassian.net/browse/WALLET-48
